---
- name: configuration | create chezmoi directory
  ansible.builtin.file:
    state: directory
    path: ~/.config/chezmoi
    mode: 0700

- name: configuration | templating chezmoi.toml
  ansible.builtin.template:
    src: chezmoi.toml.j2
    dest: ~/.config/chezmoi/chezmoi.toml
    mode: 0600
